# Generated by Django 5.2.6 on 2025-10-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_description",
            field=models.TextField(),
        ),
    ]
