# Generated by Django 5.2.6 on 2025-10-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_application", "0002_alter_item_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://theme-assets.getbento.com/sensei/cb0fd97.sensei/assets/images/catering-item-placeholder-704x520.png",
                max_length=500,
            ),
        ),
    ]
