# Generated by Django 5.2.6 on 2025-11-04 21:23

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_application", "0003_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_description",
            field=tinymce.models.HTMLField(),
        ),
    ]
