# Generated by Django 5.2.6 on 2025-11-05 00:57

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_application", "0005_item_item_recipe_alter_item_item_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_description",
            field=models.CharField(
                blank=True, default="No description available", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_recipe",
            field=tinymce.models.HTMLField(
                blank=True, default="<p>Recipe coming soon!</p>"
            ),
        ),
    ]
